databases:
  - name: animalfoop
    databaseName: animalfoop_db
    user: animalfoop
    region: singapore

services:
  - type: web
    name: animalfoop
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: animalfoop_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false